//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace json_uploadData
{
    using System;
    using System.Collections.Generic;
    
    public partial class deviceData
    {
        public int index { get; set; }
        public string dmac { get; set; }
        public int refpower { get; set; }
        public string uuid { get; set; }
        public int majorID { get; set; }
        public int rssi { get; set; }
        public int minorID { get; set; }
        public int type { get; set; }
        public System.DateTime time { get; set; }
    }
}
